-- 코드를 입력하세요
SELECT t1.ANIMAL_ID, t1.NAME
FROM ANIMAL_INS AS t1
LEFT JOIN ANIMAL_OUTS AS t2 ON t1.ANIMAL_ID = t2.ANIMAL_ID
WHERE SEX_UPON_OUTCOME IS NOT NULL
ORDER BY (t2.DATETIME - t1.DATETIME) DESC
LIMIT 2;