-- 코드를 입력하세요
SELECT
    DATE_FORMAT(SALES_DATE, '%Y') AS YEAR,
    DATE_FORMAT(SALES_DATE, '%m') AS MONTH,
    COUNT(DISTINCT B.USER_ID) AS PUCHASED_USERS,
    ROUND(
        COUNT(DISTINCT B.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE DATE_FORMAT(JOINED, '%Y') = '2021'), 1
    ) AS PUCHASED_RATIO
FROM USER_INFO A
RIGHT JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
WHERE DATE_FORMAT(JOINED, '%Y') = '2021'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;