-- 코드를 입력하세요
# with recursive를 이용한 재귀쿼리생성
WITH RECURSIVE TIMES AS (
SELECT 0 AS HOURS
UNION ALL
SELECT HOURS + 1 FROM TIMES WHERE HOURS < 23
)

SELECT HOURS, COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS
RIGHT JOIN TIMES ON DATE_FORMAT(ANIMAL_OUTS.DATETIME, '%H') = TIMES.HOURS
GROUP BY HOURS
ORDER BY HOURS;