-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK AS t1
INNER JOIN BOOK_SALES AS t2 ON t1.BOOK_ID = t2.BOOK_ID
WHERE
    YEAR(t2.SALES_DATE) = 2022
    AND MONTH(t2.SALES_DATE) = 01
GROUP BY CATEGORY
ORDER BY CATEGORY;