-- 코드를 입력하세요
SELECT
    B.AUTHOR_ID,
    AUTHOR_NAME,
    CATEGORY,
    SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK AS A
INNER JOIN AUTHOR AS B ON B.AUTHOR_ID = A.AUTHOR_ID
INNER JOIN BOOK_SALES AS C ON C.BOOK_ID = A.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m-%d') BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;