-- 코드를 입력하세요
SELECT
    APNT_NO,
    PT_NAME,
    C.PT_NO,
    B.MCDP_CD,
    DR_NAME,
    APNT_YMD
FROM APPOINTMENT AS A
INNER JOIN DOCTOR AS B ON B.DR_ID = A.MDDR_ID
INNER JOIN PATIENT AS C ON C.PT_NO = A.PT_NO
WHERE A.MCDP_CD = 'CS' AND DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD;