-- 코드를 입력하세요
SELECT DISTINCT t1.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS t1
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS t2 ON t1.CAR_ID = t2.CAR_ID
WHERE CAR_TYPE = '세단' AND MONTH(START_DATE) = 10
ORDER BY CAR_ID DESC;