-- 코드를 입력하세요
SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO
INNER JOIN REST_REVIEW AS t2 USING (REST_ID)
WHERE ADDRESS LIKE '서울%'
GROUP BY t2.REST_ID
ORDER BY
    SCORE DESC,
    FAVORITES DESC;